repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.9.3
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
    args: ['--markdown-linebreak-ext=md']
  - id: check-json
  - id: check-yaml
  - id: mixed-line-ending
    args: ['--fix=lf']
  - id: end-of-file-fixer
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.263'
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
- repo: local
  hooks:
  - id: export-requirements
    name: Export requirements.txt
    entry: poetry export --output requirements.txt --without-hashes
    language: system
    pass_filenames: false
