version: '3'
services:
  app:
    build:
      context: .
    command: bash -c "make setup && make run"
    env_file:
      .env
    environment:
      - POSTGRES_HOST=db
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:14
    env_file:
      .env
    ports:
      - 15432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
