# Generated by Django 4.2.2 on 2023-06-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=50)),
                (
                    "carrier",
                    models.CharField(
                        choices=[
                            ("DHL", "shipments.enums.carrier.dhl"),
                            ("DPD", "shipments.enums.carrier.dpd"),
                            ("GLS", "shipments.enums.carrier.gls"),
                            ("UPS", "shipments.enums.carrier.ups"),
                            ("FDX", "shipments.enums.carrier.fedex"),
                        ],
                        max_length=6,
                    ),
                ),
                ("sender_address", models.CharField(max_length=200)),
                ("receiver_address", models.CharField(max_length=200)),
                ("article_name", models.CharField(max_length=120)),
                ("article_quantity", models.IntegerField()),
                ("article_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("SKU", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=20)),
            ],
        ),
    ]
